<databaseAliasName1>:
  type: <type>
  user: <user>
  password: <password>
  database: <database>
  host: <host>
  port: <port>
  threaded: 
  serviceName: 
  sid: 
<databaseAliasName2>:
  type: <type>
  user: <user>
  password: <password>
  database: <database>
  host: <host>
  port: <port>
  threaded: 
  serviceName: 
  sid: 
<databaseAliasName3>:
  type: <type>
  user: <user>
  password: <password>
  database: <database>
  host: <host>
  port: <port>
  threaded: 
  serviceName: 
  sid: 