workers: <workers>
jobs:
  <jobAliasName1>:
    active: <active>
    predecessors:
    -
    database: <database>
    table: <table>
    defaultColumnValues:
    identifierColumns:
    -
    scrambleColumns:
    -
    randomColumns:
    -
    randomSalt: <randomSalt>
    allDataRandom: <allDataRandom>
    preTargetAdhocQueries:
    -
    postTargetAdhocQueries:
    -
  <jobAliasName2>:
    active: <active>
    predecessors:
    -
    database: <database>
    table: <table>
    defaultColumnValues:
    identifierColumns:
    -
    scrambleColumns:
    -
    randomColumns:
    -
    randomSalt: <randomSalt>
    allDataRandom: <allDataRandom>
    preTargetAdhocQueries:
    -
    postTargetAdhocQueries:
    -
  <jobAliasName3>:
    active: <active>
    predecessors:
    -
    database: <database>
    table: <table>
    defaultColumnValues:
    identifierColumns:
    -
    scrambleColumns:
    -
    randomColumns:
    -
    randomSalt: <randomSalt>
    allDataRandom: <allDataRandom>
    preTargetAdhocQueries:
    -
    postTargetAdhocQueries:
    -
